name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn==1.7.2
      - matplotlib
      - seaborn
      - mlflow==2.19.0
